### PR TITLE
Add changelog for release v0.2.0

### LINKED ISSUE #118: Release v0.2.0
We added quite a few contributions in since the last release.

- [ ] Release and test a candidate for 0.2.0 release. 
- [ ] Release v0.2.0

### PR DESCRIPTION
**Pull request by LiorLieberman**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This adds the changelog for v0.2.0. Consensus on this PR means approval for v0.2.0 release

**Which issue(s) this PR fixes**:

Fixes #118 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/cc @levikobi @mlavacca

### CODE REVIEW

**Review by mlavacca — APPROVED** [review]
It looks good to me!
/approve

**Review by levikobi — APPROVED** [review]
/lgtm

**Pull request merged**
