### PR TITLE
example: add canary ingress case

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

- [ ] Update Quickstart Docs

Sub of #9

**Which issue(s) this PR fixes**:

Fixes

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Xunzhuo** [comment]
xref: https://github.com/kubernetes-sigs/ingress2gateway/issues/21

**Comment by robscott** [comment]
Hey @Xunzhuo, not sure I understand what this is doing. Is this supposed to be test input?

**Comment by Xunzhuo** [comment]
Hey @robscott, #16 #17 are used for examples to let users to have a quickstart after installing i2gw.

**Comment by robscott** [comment]
@Xunzhuo let us know if you want to follow up on these, for now I'm going to close out in favor of more recent PRs.

**Pull request closed without merging**
