### PR TITLE
Add ingressonly flag

### LINKED ISSUE #67: Add a `ingresses-only` flag
**What would you like to be added**:
Add a `ingresses-only` flag to scope the tool to only convert resources without looking for providers CRDs

**Why this is needed**:
Provider specific support is in early stage support now with only few providers support the conversion. Users might want to scope the tool invocation to only read and convert their ingresses

/label good-first-issue
/help-wanted

### PR DESCRIPTION
**Pull request by camperjett**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
this adds a new flag ingresses-only to scope the tool to only convert resources without looking for providers CRDs

**Which issue(s) this PR fixes**:

Fixes #67 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by camperjett** [comment]
@levikobi my last pull-request got closed due to removal of commit from my end. Could you PTAL?

**Comment by LiorLieberman** [comment]
Thanks @camperjett ! 

Thinking about this more, `ingresses-only` is a bit different than not doing providers specific logic.
Provider specific logic should be looking at specific ingresses annotations and CRDs if any. 

I think we should have both functionalities; 

1. not doing provider specific logic - this should maybe be called `core-only` or something like this (I am open for suggestions)
2. doing only Ingresses logic, regardless of whether it has provider specific annotations or not. This flag should work together with the providers flag which tells the tool which providers logic to execute. 

@levikobi feel free to loop in

**Comment by levikobi** [comment]
> Thanks @camperjett !
> 
> Thinking about this more, `ingresses-only` is a bit different than not doing providers specific logic. Provider specific logic should be looking at specific ingresses annotations and CRDs if any.
> 
> I think we should have both functionalities;
> 
> 1. not doing provider specific logic - this should maybe be called `core-only` or something like this (I am open for suggestions)
> 2. doing only Ingresses logic, regardless of whether it has provider specific annotations or not. This flag should work together with the providers flag which tells the tool which providers logic to execute.
> 
> @levikobi feel free to loop in

I'm not sure I got your second point TBH, @LiorLieberman 
Do you mean `ingress-only` flag is going to convert everything (including provider-specific annotations) but provider-specific CRDs?

**Comment by LiorLieberman** [comment]
Yes

**Comment by LiorLieberman** [comment]
Hi @camperjett 👋, just checking in. Let us know if you need any help moving this forward.

**Comment by camperjett** [comment]
Hi. Yeah I'll update asap.

**Comment by LiorLieberman** [comment]
Hey @camperjett, a friendly ping, do you still have the capacity to work on this?

**Comment by YIHONG-JIN** [comment]
Hi @camperjett, are you still working on this? If this issue is still open, I can take over if you don't have capacity to do this.

**Pull request closed without merging**
