### PR TITLE
feat: Add Download from GitHub Release

### PR DESCRIPTION
**Pull request by dierbei**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Help me developers find the download address of the app version.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by LiorLieberman** [comment]
Thanks @dierbei

We don't have release workflow configured yet, and the github releases are empty.

I'd prefer having releases first before adding this section. 

Is it something you'd be interested doing?

**Comment by dierbei** [comment]
@LiorLieberman I will try to solve the release workflow problem.

Can you give me some suggestions? For example: required architecture, compressed package.

or some other suggestions

**Comment by LiorLieberman** [comment]
@dierbei I am closing this as we have now the github releases and reference to them in the installation section. 

Thanks for this and for the previous PRs! Feel free to look for other open issues and comment if there is anything you like/want to take. Happy to help whenever needed!

**Pull request closed without merging**
