### PR TITLE
add boilerplate templates and verification

### PR DESCRIPTION
**Pull request by LiorLieberman**
**What type of PR is this?**

not sure what kind is, will go without one

**What this PR does / why we need it**:
adding boilerplate templates and hack/verify-boilerplate.sh

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE

```

### CODE REVIEW

**Review by robscott — COMMENTED** [review]
Thanks for adding this @LiorLieberman! Mind adding this to the makefile to ensure it actually runs as a presubmit? Could either add here: https://github.com/kubernetes-sigs/ingress2gateway/blob/main/Makefile#L53, or pull in the `verify-all` script we're using in GW API: https://github.com/kubernetes-sigs/gateway-api/blob/main/hack/verify-all.sh

**Comment by LiorLieberman** [comment]
Thanks! As discussed offline, we do not have presubmits configured for ingress2gateway now. 

Will add it tomorrow and ping for a review again.

**Comment by LiorLieberman** [comment]
attempt to add the presubmits: https://github.com/kubernetes/test-infra/pull/29895/files

**Comment by robscott** [comment]
Thanks @LiorLieberman! This change LGTM, but it looks like we need to fix some things before this can actually merge.

/approve

**Comment by LiorLieberman** [comment]
This is blocked by https://github.com/kubernetes-sigs/ingress2gateway/pull/29

Once this merged, I will rebase.

**Comment by robscott** [comment]
Thanks @LiorLieberman!

/lgtm

**Pull request merged**
