### PR TITLE
feat: deprecate i2gw.InputResources

### LINKED ISSUE #113: Find a good use of i2gw.InputResources or deprecate it
**What would you like to be added**:
We need to revisit the decision to use `i2gw.InputResources` struct or deprecate it altogether.

**Why this is needed**:
Currently this struct only holds a list of Ingresses, I couldn't think of a reason we will need other resources as input resources. 
I think this was added originally to be able to support CRD propagation to providers but since we move to a "fetch and store" per provider logic we need to revisit whether this is needed. 

Another sub task that comes with it is changing `ToGatewayAPI` function signature  on the Provider interface as the input resources are no longer in use after https://github.com/kubernetes-sigs/ingress2gateway/pull/112

- [ ] Find a good use of i2gw.InputResources or deprecate it
- [ ] Remove input resources from [ToGatewayAPI](https://github.com/kubernetes-sigs/ingress2gateway/blob/654e76fa2ec341b9eaf9f7ba42f12e3305c7b993/pkg/i2gw/provider.go#L73C2-L73C14) function.

### PR DESCRIPTION
**Pull request by YTGhost**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

- [x] Deprecate i2gw.InputResources
- [x] Remove input resources from [ToGatewayAPI](https://github.com/kubernetes-sigs/ingress2gateway/blob/654e76fa2ec341b9eaf9f7ba42f12e3305c7b993/pkg/i2gw/provider.go#L73C2-L73C14) function.

**Which issue(s) this PR fixes**:

Fixes #113 

**Does this PR introduce a user-facing change?**:

```release-note
Deprecate `i2gw.InputResources` and remove input resources from `ToGatewayAPI` function
```

### CODE REVIEW

**Comment by YTGhost** [comment]
Hi @LiorLieberman PTAL

**Comment by YTGhost** [comment]
> Thats awesome, thank you @YTGhost ! /ok-to-test
> 
> In the meantime, please update the release notes

Sure

**Review by LiorLieberman — COMMENTED** [review]
This PR looks good to me. 
/cc @levikobi @mlavacca can you please take a look?

**Review by levikobi — COMMENTED** [review]
Thanks @YTGhost 
This is quite a big change so I played around with this for a bit. I Couldn't find something that broke and tests are passing so lgtm.

@mlavacca if you could take a look as well it would be great
/lgtm

**Review by mlavacca — APPROVED** [review]
Thanks YTGhost!

/lgtm

**Pull request merged**
