### PR TITLE
Add instructions for installing binary via Homebrew

### PR DESCRIPTION
**Pull request by b-reich**
Added instructions for installing the binary via Homebrew on macOS and Linux to make it easier for users to obtain the `ingress2gateway` binary. This provides an alternative method to building from the source.

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Added instructions for installing the binary via Homebrew on macOS and Linux tomake it easier for users to obtain the  ingress2gateway binary. This provides an alternative method to building from the source.
https://github.com/Homebrew/homebrew-core/pull/166817

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
Thanks !

**Review by levikobi — COMMENTED** [review]
Thank you for adding this @b-reich!
We have a `release` file, can you please add a step there to describe how to update homebrew upon a new release?

**Comment by b-reich** [comment]
> Thank you for adding this @b-reich! We have a `release` file, can you please add a step there to describe how to update homebrew upon a new release?

Normally nothing needs to be done for this. This happens automatically in the CI of Homebrew.

**Comment by b-reich** [comment]
I can still add a manual upgrade guide if desired. It will probably just never be needed.

**Comment by levikobi** [comment]
@b-reich nice, I wasn't aware of that. No need to add instructions then.
/lgtm
/cc @LiorLieberman

**Comment by LiorLieberman** [comment]
Thanks @b-reich, thats great! 
/approve

**Pull request merged**
