### PR TITLE
added ability to respect the kubebuilder maxlimit

### LINKED ISSUE #124: Make sure generated Gateway-API object fields obey kubebuilder max item validation
**What would you like to be added**:
Add a mechanism that considers the kube-builder max item validation on Gateway-API list fields. See [this for example](https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/httproute_types.go#L223). 

One option is to validate the constraint, and if it is exceeded - throw an appropriate message.
Another option is to add conversion logic that splits objects by these constraints, which will be more challenging.

**Why this is needed**:
To help migrating users who violate those constraints. See https://github.com/kubernetes-sigs/gateway-api/issues/2501 as an example.

### PR DESCRIPTION
**Pull request by swastik959**
**What type of PR is this?**

/kind feature
**What this PR does / why we need it**:
adds the ability to limit of objects to respect the kubebuilder max count
**Which issue(s) this PR fixes**:

Fixes #124 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by swastik959** [comment]
hi @levikobi I have tried to create a pr for the feedback if this is what was meant from the issue ?

**Review by levikobi — COMMENTED** [review]
Hi @swastik959! Thank you for taking on this one.

The maxlimit constant isn't provider-specific limitation. We either need to add this as a common validation to each provider, or (a better approach IMO) check that after the translation already occurred.

Also, please avoid the use of panic.

**Comment by LiorLieberman** [comment]
@swastik959 Do you still work on this? Let us know if we can help you to move this forward

**Comment by LiorLieberman** [comment]
I am going to close the PR un-assign this now, so others can pick it up. Feel free to reply if you still want to work on this.

**Pull request closed without merging**
