### PR TITLE
i2gw binary added to .gitignore

### PR DESCRIPTION
**Pull request by mlavacca**
**What type of PR is this?**

**What this PR does / why we need it**:

The `ingress2gateway` binary created by `make build` is added to the `.gitignore`.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by levikobi — APPROVED** [review]
Thanks @mlavacca 
/lgtm

**Review by Xunzhuo — APPROVED** [review]
/lgtm

**Comment by robscott** [comment]
Thanks @mlavacca!

**Pull request merged**
